# Site settings
title: "Bombastic Blastin' Beats"
baseurl: ""
url: "http://reidcooper.github.io"
email: "mailto:reid.cooper8+github@gmail.com"
github: "https://github.com/reidcooper/"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname:
